server:
  applicationConnectors:
    - type: http
      port: {{cfg.server.http}}
  adminConnectors:
    - type: http
      port: {{cfg.server.admin}}
logging:
  level: {{cfg.logging.level}}
  loggers:
    io.dropwizard: INFO
    com.bmontague.helloworld: DEBUG
  appenders:
    - type: console

name: "{{cfg.service.name}}"
