server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081
logging:
  level: {{cfg.logging.level}}
  loggers:
    io.dropwizard: INFO
    com.bmontague.helloworld: DEBUG
  appenders:
    - type: console

name: "{{cfg.server.name}}"
